In [1]:
#### 1. Import the numpy package under the name `np` (★☆☆)


import numpy as np


In [2]:
#### 2. Create a null vector of size 10 (★☆☆)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
np.zeros(10)
x = np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [4]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
x = np.arange(0,9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)


A = [1,2,0,0,4,0]
np.nonzero(A)


(array([0, 1, 4]),)

In [7]:
#### 7. Create a 3x3 identity matrix (★☆☆)
npeye= np.eye(3,3)
npeye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
#### 8. Create a 3x3x3 array with random values (★☆☆)
np.random.random([3,3,3])

array([[[0.08430716, 0.09927432, 0.96678068],
        [0.21434739, 0.72301801, 0.87012143],
        [0.29806788, 0.97816464, 0.66657149]],

       [[0.07531149, 0.24393109, 0.09516321],
        [0.46202164, 0.64773446, 0.10043575],
        [0.83698206, 0.367787  , 0.02585721]],

       [[0.35599523, 0.64344409, 0.2067267 ],
        [0.73905786, 0.93221403, 0.20756884],
        [0.68095114, 0.74318968, 0.98430527]]])

In [9]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
array_10x10 = np.random.random([10,10])
array_10x10.min()
array_10x10.max()

0.9932290161609234

In [20]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
random_vector = np.random.random(30)
print(random_vector)
random_vector.mean()

[0.31618496 0.49465938 0.61536777 0.7048849  0.78867822 0.6492134
 0.18322631 0.27585906 0.16847648 0.59668525 0.03847149 0.01378974
 0.15105786 0.58049291 0.30841684 0.70466936 0.36016183 0.33340079
 0.69205998 0.90626749 0.72182743 0.52462298 0.30178292 0.51626368
 0.45870573 0.88550897 0.94876196 0.67203801 0.29209199 0.65533542]


0.4952987705545839

In [11]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
matrix_5_5 = np.diag(1+np.arange(4), k=-1)
matrix_5_5

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [12]:
#### 12. Normalize a 5x5 random matrix (★☆☆)
normalized_5x5_matrix = np.random.random((5,5))
min = normalized_5x5_matrix.min()
max = normalized_5x5_matrix.max()

normalize = (normalized_5x5_matrix-min) / (max-min)
print(normalize)

[[0.94432599 0.47772514 0.17126001 0.43520026 0.03109459]
 [0.96164161 0.13403879 0.29292475 0.74376014 0.40545042]
 [0.71221476 0.65100143 0.99235411 0.88048505 1.        ]
 [0.72217885 0.51116875 0.5156662  0.         0.13212112]
 [0.53958591 0.03760906 0.59769604 0.28764554 0.73668131]]


In [13]:
#### 13. How to find common values between two arrays? (★☆☆)
a = np.arange(0,6)
b = np.arange(2,9)

common_values = np.intersect1d(a,b)
common_values

array([2, 3, 4, 5])

In [14]:
#### 14. Create a random vector of size 10 and sort it (★★☆)
c = np.random.random(10)

c.sort()

print(c)

[0.09963044 0.16699137 0.39383512 0.39727583 0.45958996 0.51577011
 0.56096989 0.72418682 0.7599368  0.89417734]


In [15]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
random_vector = np.random.random(10)
random_vector[random_vector.argmax()] = 0
random_vector

array([0.        , 0.37196352, 0.57464543, 0.32965165, 0.83301305,
       0.23788023, 0.46985698, 0.89769405, 0.44644781, 0.12707114])

In [16]:
#### 16. Subtract the mean of each row of a matrix (★★☆)
matrix = np.arange(0,4).reshape(2,2)
matrix


array([[0, 1],
       [2, 3]])

In [17]:
z = matrix - matrix.mean(axis=1,keepdims=True)
z

array([[-0.5,  0.5],
       [-0.5,  0.5]])

In [18]:
#### 17. How to get the n largest values of an array (★★★)
#hint: np.argsort | np.argpartition`
Y = np.arange(10000)
np.random.shuffle(Y)
n = 5

Y[np.argsort(Y)[-5:]]


array([9995, 9996, 9997, 9998, 9999])

In [19]:
#Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36 )

matrix_5_3 = np.random.randint(15, size=(5,3))
print(matrix_5_3)
#h = matrix_5_3[matrix_5_3 > 4]
#h
h = np.where(matrix_5_3 > 4, matrix_5_3*matrix_5_3, matrix_5_3)
print(h)

[[ 8  3  4]
 [ 2  1  9]
 [10 10 13]
 [ 7 13 13]
 [12  8 11]]
[[ 64   3   4]
 [  2   1  81]
 [100 100 169]
 [ 49 169 169]
 [144  64 121]]
