In [2]:
#### 1. Import the numpy package under the name `np` (★☆☆)


import numpy as np


In [3]:
#### 2. Create a null vector of size 10 (★☆☆)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
np.zeros(10)
x = np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [5]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
x = np.arange(0,9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)


A = [1,2,0,0,4,0]
np.nonzero(A)


(array([0, 1, 4]),)

In [8]:
#### 7. Create a 3x3 identity matrix (★☆☆)
npeye= np.eye(3,3)
npeye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
#### 8. Create a 3x3x3 array with random values (★☆☆)
np.random.random([3,3,3])

array([[[0.97024031, 0.37001028, 0.81553157],
        [0.4750479 , 0.66520147, 0.90580717],
        [0.29714672, 0.57151047, 0.65196209]],

       [[0.84183986, 0.7573616 , 0.82578446],
        [0.9988072 , 0.67451815, 0.73708331],
        [0.02676169, 0.62952904, 0.61639971]],

       [[0.20393425, 0.60400181, 0.79835088],
        [0.20548798, 0.18075787, 0.69095896],
        [0.54294228, 0.97069515, 0.72163928]]])

In [18]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
array_10x10 = np.random.random([10,10])
array_10x10.min()
array_10x10.max()

0.9567844187595737

In [19]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
random_vector = np.random.random(30)
print(random_vector)
random_vector.mean(
    
)

[0.77190077 0.41003457 0.61752927 0.27911562 0.29136271 0.72677742
 0.48780026 0.80969877 0.1694787  0.24948146 0.10927287 0.4792534
 0.96123462 0.97224894 0.97428997 0.7072405  0.87472332 0.76522059
 0.85536946 0.69078082 0.74902162 0.06933904 0.50287907 0.29421881
 0.73537215 0.93525179 0.35031218 0.48072984 0.95494437 0.42225001]


0.5899044306742421

In [21]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
matrix_5_5 = np.diag(1+np.arange(4), k=-1)
matrix_5_5

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [30]:
#### 12. Normalize a 5x5 random matrix (★☆☆)
normalized_5x5_matrix = np.random.random((5,5))
min = normalized_5x5_matrix.min()
max = normalized_5x5_matrix.max()

normalize = (normalized_5x5_matrix-min) / (max-min)
print(normalize)

[[0.10035599 0.63967973 0.         0.96889673 0.59277257]
 [0.96978704 0.35059253 0.44895242 0.39379694 0.82267959]
 [0.22604503 0.77901131 0.1875534  0.92705914 0.2491067 ]
 [0.09735456 0.42359202 0.53392248 0.50417986 0.90534315]
 [0.56658625 0.54061737 1.         0.98568442 0.64116705]]


In [36]:
#### 13. How to find common values between two arrays? (★☆☆)
a = np.arange(0,6)
b = np.arange(2,9)

common_values = np.intersect1d(a,b)
common_values

array([2, 3, 4, 5])

In [46]:
#### 14. Create a random vector of size 10 and sort it (★★☆)
c = np.random.random(10)

c.sort()

print(c)

[0.24052908 0.30376472 0.3810652  0.51663237 0.74065404 0.79525291
 0.83976022 0.85257527 0.90672261 0.94850721]


In [55]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
random_vector = np.random.random(10)
random_vector[random_vector.argmax()] = 0
random_vector

array([0.29828326, 0.61903153, 0.55961535, 0.70470306, 0.        ,
       0.02974828, 0.62947555, 0.17496779, 0.43528856, 0.88383548])

In [70]:
#### 16. Subtract the mean of each row of a matrix (★★☆)
matrix = np.arange(0,4).reshape(2,2)
matrix


array([[0, 1],
       [2, 3]])

In [71]:
z = matrix - matrix.mean(axis=1,keepdims=True)
z

array([[-0.5,  0.5],
       [-0.5,  0.5]])

In [87]:
#### 17. How to get the n largest values of an array (★★★)
#hint: np.argsort | np.argpartition`
Y = np.arange(10000)
np.random.shuffle(Y)
n = 5

Y[np.argsort(Y)[-5:]]


array([9995, 9996, 9997, 9998, 9999])

In [107]:
#Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36 )

matrix_5_3 = np.random.randint(15, size=(5,3))
print(matrix_5_3)
#h = matrix_5_3[matrix_5_3 > 4]
#h
h = np.where(matrix_5_3 > 4, matrix_5_3*matrix_5_3, matrix_5_3)
print(h)

[[ 4 13  3]
 [ 5  5  9]
 [ 0  7  6]
 [14 12 13]
 [ 0  2  2]]
[[  4 169   3]
 [ 25  25  81]
 [  0  49  36]
 [196 144 169]
 [  0   2   2]]
